#!/usr/bin/env node

const { spawn } = require('child_process')
const { resolve } = require('path')
const cli = resolve(__dirname, '..', 'dist', 'index.js')
const args = process.argv.slice(2).join(' ')
const cmd = `${cli} ${args}`
spawn('node', cmd.split(' '), { detached: true, stdio: 'inherit', cwd: process.cwd() })
